# Generated by Django 6.0.2 on 2026-03-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyroom",
            name="invite_code",
            field=models.CharField(max_length=20, unique=True, null=True, blank=True),
        ),
    ]
