# Generated by Django 6.0.2 on 2026-03-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_studyroom_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyroom",
            name="invite_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
