# Generated by Django 6.0.2 on 2026-03-12 04:25

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_studyroom_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyroom",
            name="invite_code",
            field=models.CharField(
                blank=True,
                default=rooms.models.generate_code,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
