# Generated by Django 6.0.2 on 2026-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_channel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('gray', 'Gray')], default='purple', max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
