# Generated by Django 6.0.2 on 2026-02-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_edited_at_message_flag_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="message",
            name="reply_to",
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="flag_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
