# Generated by Django 6.0.2 on 2026-02-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_options_message_deleted_at_and_more"),
        ("chat", "0003_remove_message_is_read_remove_message_reply_to_and_more"),
    ]

    operations = []
