# Generated by Django 6.0.2 on 2026-03-12 00:33

import chat.models
import chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_merge_20260226_0229"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=chat.models.upload_to_uuid,
                validators=[chat.validators.validate_uploaded_file],
            ),
        ),
    ]
