# Generated by Django 6.0.2 on 2026-02-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                default="avatars/default.png", upload_to="avatars/"
            ),
        ),
    ]
