# Generated by Django 5.2.11 on 2026-03-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyRoom',
        ),
    ]
