# Generated by Django 5.2.11 on 2026-03-09 21:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorosession',
            name='minutes_remaining',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='cycles_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('paused', 'Paused'), ('break', 'Break'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
