# Generated by Django 6.0.2 on 2026-03-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_studyroom"),
        ("accounts", "0003_remove_pomodorosession_minutes_remaining_and_more"),
    ]

    operations = []
