# Generated by Django 6.0.1 on 2026-02-16 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('paused', 'Paused'), ('break', 'Break')], default='not_started', max_length=20)),
                ('minutes_remaining', models.PositiveIntegerField(default=25)),
                ('session_duration', models.PositiveIntegerField(default=25)),
                ('break_duration', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
