# Generated by Django 6.0.1 on 2026-02-16 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_members', models.ManyToManyField(blank=True, related_name='active_in_rooms', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='study_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
