# Generated by Django 6.0.2 on 2026-03-12 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studychannel",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="rooms.studyroom",
            ),
        ),
        migrations.AlterField(
            model_name="studychannel",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
